"""initial schema

Baseline revision. The template ships no tables, so this migration is
intentionally empty -- it exists so future autogenerated revisions have a
stable `down_revision` to chain from.

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-09-27 00:00:00.000000

"""
from typing import Sequence, Union

revision: str = "001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
